[versions]
agp = "8.13.0"
kotlin = "2.0.21"
#kotlin = "1.9.20" # Or your project's version

coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
appcompatVersion = "1.7.1"
googleGmsGoogleServices = "4.4.2"
firebaseDatabase = "22.0.1"
firebaseFirestoreKtx = "26.0.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
#appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompatVersion" }
#firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
#firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
# Add the kotlin-parcelize plugin here
#kotlin.parcelize = { id = "kotlin-parcelize" }  # ✅ add this line
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
#google-gms-google-services = { id = "com.google.gms.google-services", version = "4.4.2" }


